### PR TITLE
Issue prevents RVIZ from loading current STL files

### PR DESCRIPTION
**Pull request by cpaxton**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Is this to fix a "ascii vs binary stl and `solid` in the header" problem?

**Comment by cpaxton** [comment]
That was the goal, yeah.

**Comment by gavanderhoorn** [comment]
So why close it? :)

**Comment by cpaxton** [comment]
I'm not sure why the integration is failing or the meshes won't show here on github. It was a pretty minor change: I just got rid of the "solid" and replaced with a "robot" tag.

**Comment by gavanderhoorn** [comment]
Travis failing is a configuration issue with the repository, not your fault.

> [..] or the meshes won't show here on github.

What do you mean?

**Comment by shaun-edwards** [comment]
@gavanderhoorn, the file's changed tab doesn't show the model diff.  The diff is likely empty since there isn't a geometry difference.

@cpaxton, I think this is worth merging if the models don't load in Rviz (that's the whole point of the models).

**Comment by v4hn** [comment]
We had no problem with these meshes for the last year, i.e. they show(and showed) up in RViz.
Hence, I'm not sure what this request is supposed to fix.

@gavanderhoorn could you describe and provide a picture of the problem?

**Comment by shaun-edwards** [comment]
@cpaxton, is this still an issue or can this PR be closed.  @v4hn's comment seems to indicate that it isn't an issue.

**Comment by cpaxton** [comment]
Closed the issue. It may be a quirk of one of our platforms. We use a lot of custom code, including custom RVIZ forks and ros-hydro. If I notice it in vanilla rviz in ros-indigo I will provide more documentation.

**Pull request closed without merging**
