### PR TITLE
Added type check to response in getStatus

### PR DESCRIPTION
**Pull request by orikuma**
When I use baseSModel.py and execute sendCommand to robotiq s model in short time, getStatus failes by following error.
I could avoid this error by this changes, but I think it is not good that getStatus has while loop in itself and I want to know why read_input_registers returns WriteMultipleRegistersResponse.
Is this problem caused by RobotiqHand firmware or pymodbus?

```
File "/home/leus/ros/hydro/src/ros-industrial/robotiq_s_model_control/src/robotiq_s_model_control/baseSModel.py", line 155, in getStatus
    status = self.client.getStatus(16);
File "/home/leus/ros/hydro/src/ros-industrial/robotiq_modbus_tcp/src/robotiq_modbus_tcp/comModbusTcp.py", line 89, in getStatus
    output.append((response.getRegister(i) & 0xFF00) >> 8)
AttributeError: 'WriteMultipleRegistersResponse' object has no attribute 'getRegister'
```

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@nicolaslauzier, Do you have comment on this?

**Comment by nicolaslauzier** [comment]
The problem is with pymodbus, or its use. The probable cause is that the request was that the request for "WriteMultipleRegistersResponse" was sent but the answer was not received in time due to some delay on the network (or error in the messages). A new request was sent but the echo message (acknowledgment) for the write request was received after the new request was sent.

Checking the type of the answer is a working solution but I think it would be better to wait for the echo message to be received before sending a new request. Can you take a look at this solution? I can help if you are not familiar with pymodbus.

**Comment by shaun-edwards** [comment]
@orikuma, ping

**Comment by orikuma** [comment]
I'm sorry for the delay in contact.
This problem was caused by my use in sending requests.
I used sendCommand() in ros subscriber callback function and getStatus() in main loop.
When a read request was sent by getStatus in main loop immediately after a write request was sent by sendCommand in callback, response in getStatus receive response to write request and reported error occured.
Therfore, I think the correct solution for this problem is introducing exclusive control like threading.Lock before sending request by sendCommand, getStatus etc in user functions.
Thank you for your kind support.

**Comment by shaun-edwards** [comment]
@orikuma, Thank you for the quick reply and the update.  It sounds like this should be logged as an issue against the robotiq package.  I'm not sure that the robotiq package was written with thread safety in mind, but adding it would avoid this issue.  I'd like to understand how critical this issue is.  Have you been able to work around the issue or is it preventing you from utilizing the robotiq library?

By the way, I really appreciate you using the robotiq libraries and offering up feedback when it doesn't meet you needs.

**Comment by orikuma** [comment]
I could noticed the cause of this problem and deal with it by your advice to wait for the echo message to be received before sending a new request.
Now, I have been able to work around the problem and I am using the robotiq library without problems.

I think this problem is critical in use because comModbusTcp is terminated forcely by this error.
In addition, I think this problem likely to happen in other user programs because sendCommand is probably used in subscriber callback.
I cannot have the conviction whether thread safety should be guaranteed in comModbusTcp (ex. add threading.Lock to communication class in comModbusTcp) or in user functions, but It would be helpful to let user know whether the robotiq library considers thread safety or not.

**Comment by nicolaslauzier** [comment]
Is your workaround part of SModelTcpNode.py? Do you think you can commit it to the repo so that we can make it part of the library?

Thanks!

**Comment by orikuma** [comment]
My workaround is for communication class in comModbusTcp.py, not SModelTcpNode.py.
I simply added threading.Lock() exclusive control to communication class to avoid reported error.
Please check the changes. Thanks.

**Comment by shaun-edwards** [comment]
@nicolaslauzier , It looks like @orikuma , has update his PR.  Can you review?  Thanks in advance!

**Comment by nicolaslauzier** [comment]
The modification is very nice. It's indeed the proper way of implementing it (it is way better than having delays). I should have done that from the beginning but I wasn't experiencing the issue and I'm not familiar with threading in Python.

I think that we should merge this to the trunk. @shaun-edwards, can you do that?

Thanks @orikuma  for this modification!

Nicolas

**Comment by shaun-edwards** [comment]
Thanks @orikuma & @nicolaslauzier

**Pull request merged**
