### PR TITLE
Syncing changes from hydro to indigo branch

### PR DESCRIPTION
**Pull request by shaun-edwards**
Seems the hydro/indigo branch are out of sync.  This pulls several changes from hydro into indigo (the main development branch).

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@gavanderhoorn, it looks like you had some comments above that got automatically added to the PR.  Not sure if these were addressed.  Maybe they should be before we do this PR to sync things back up.

**Comment by gavanderhoorn** [comment]
Not sure what is going on there. Perhaps I commented on the commit itself, instead of only within the context of the PR.

Afaict, the pkg manifests are ok.

**Comment by gavanderhoorn** [comment]
Ah, now I remember: in that particular commit, a duplicate `run_depend` was introduced. Later commits (some of my own actually) have rectified that.

I've removed the two comments (from the commits themselves).

**Comment by shaun-edwards** [comment]
@nicolaslauzier, can you please merge this?  BTW, this mis-sync was caused by myself.  @Jmeyer1292 PR was issued against hydro and I missed it.

**Pull request merged**
