### PR TITLE
kinetic-devel release

### PR DESCRIPTION
**Pull request by AustinDeric**
DO NO MERGE: Not tested on hardware.  

This PR addresses #89 and #81.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@AustinDeric, just saw this...perhaps again for the first time.  Come bug me tomorrow, and we can go over it.  Sorry for the lack of response on my part.

**Comment by felixvd** [comment]
Any update?

**Comment by AustinDeric** [comment]
@felixvd I don't have a robotiq gripper to test this code on.  If you do, can you test it and report the results?

**Comment by felixvd** [comment]
We have a 85-model gripper which isn't in these packages, I believe, but in principle sure. Can you tell me what needs testing exactly?

**Comment by jproberge** [comment]
Hi! 

I'll test this code by the end of this week (I have their 2-finger gripper, their 3-finger gripper and an FT-300 at my office). I'll go over all the changes and report back sometime during next week. Thanks!

**Comment by jproberge** [comment]
Ok, so I've finished testing all Robotiq's products (FT300 + 2F & 3F gripper) with this PR and everything seems to work just fine except for what I've already mentionned in #99 and #100 , that is, a bad reference to the "robotiq_hand.urdf.xacro" file which doesn't exist anymore.

Now unfortunately another problem is, this PR is really out of date with the current jade-devel branch. It is 50 commits behind the official branch and I wouldn't even consider to try to update the kinetic-devel branch on AustinDeric/robotiq for an eventual merge, as there will be many file conflicts and probably a lot of errors to fix as well.

So what I propose to do next to still (finally) achieve the kinetic-devel branch, is that I'll create a new kinetic-devel branch on this repo at the beginning of next week, simultaneously accompanied with a new pull request for that branch containing all the modifications from this PR (which are mostly about updating package.xml and CMakelists.txt files) along with some other mostly-aesthetic modifications that Robotiq directly asked me to make. Jade-devel is already compiling on ros-kinetic when one takes care of installing the soem dependency. I'll make sure that all the modifications compile properly and passes the proper Travis ci checks before I'll create the new PR and I guess that would then make a first viable kinetic-devel release.

**Comment by jproberge** [comment]
Finally, I'm done! :) Sorry it took way longer than expected as it turned out there was a lot of modifications to be tested. Anyway, as I said I would do, I've made my changes, tested all of them on hardware and I've created a new PR that successfully passes the Travis-ci tests. I'm now closing this PR as I consider it has now been superseeded by PR #130 . Thanks !

**Pull request closed without merging**
