### PR TITLE
Indigo devel

### PR DESCRIPTION
**Pull request by HashirShafi**
This PR is intended to solve the CMake error issue of soem package dependency. I am attaching the edited CMakeListst.txt which worked for me. 
[CMakeLists.txt](https://github.com/ros-industrial/robotiq/files/334390/CMakeLists.txt)

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@HashirShafi, Thanks for the contribution.  Can you please rebase this on the `jade-devel`?  Let me know if you need help with this?

**Comment by HashirShafi** [comment]
@shaun-edwards  I am sorry. I am new to ROS and Github. Do you mean to test it on jade distribution by 'rebase' ?

**Comment by shaun-edwards** [comment]
@HashirShafi, I'm not sure what happened.  It looks like you want to sync the `indigo-devel` and `jade-devel`.  This needs to be done, but I will do this.  Your changes to fix the compile issue seem to have been lost.  You can try again, or you can simply send the changes to me and I will create the PR for you.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: the `CMakeLists.txt` mentioned in the OP is actually a link to an attachment (ie: just as you would attach an image to an issue). The changes to `robotiq_ethercat/CMakeLists.txt` are not included in the PR.

**Comment by HashirShafi** [comment]
@Shaun Edwardsmailto:notifications@github.com, What I have identified so far that it was the dependency issue of soem package. After having cloned the robotiq repository, I typed in the terminal

rosdep install --from-paths /my workspace's src's path/ --ignore-src

This command installed the soem package for me but it was not a catkin package so I changed the CMakeLists.txt of robotiq_ethercat package. I am attaching the modified CMakelists.txt with the email. After doing these changes I built my workspace succesfully.

**Comment by shaun-edwards** [comment]
Closing this PR because it is blocking a sync between indigo and jade.

**Pull request closed without merging**
