### PR TITLE
Adds FT300 Support

### PR DESCRIPTION
**Pull request by UltronDestroyer**
I believe, this PR adds FT300 support to the jade-devel branch. We may have to go through and see what's  happening in the .dae file as I'm quite unsure. It's old code for me - perhaps I could get some help if I missed anything.

Thanks dudes!

### CODE REVIEW

**Comment by shaun-edwards** [comment]
I believe the FT300 is already supported (although I don't have the hardware).  It looks like this PR just adds a `ftdi_id` to the method calls.

**Comment by angadhn** [comment]
Hi @TheClearpathDash or @TheDash, I was just wondering if you have tested tihs on the FT300 hardware as I'd like to use this.

**Comment by jproberge** [comment]
Closing this since it is outdated and has been superseded by other PRs.

**Comment by Danfoa** [comment]
Since I wasn't able to find the URDF models, I add them on pr #138 (Check last comments)

**Pull request closed without merging**
