### PR TITLE
Melodic port

### PR DESCRIPTION
**Pull request by christian-rauch**
This PR adapts the Robotiq S code to the new socketcan_interface and Gazebo 9 API.

Edit: This will break `kinetic` builds. Can you create a `melodic-devel` branch and a `melodic` CI configuration?

### CODE REVIEW

**Comment by jproberge** [comment]
@christian-rauch : Sure and thanks! This is a great PR. Let me 2-3 days and I'll review it & create a new branch if testing was successful. I'll get back to you very soon.

**Comment by gavanderhoorn** [comment]
@jproberge: if possible we try to avoid branching.

If these changes are compatible with Kinetic *or* we can `ifdef` or use some other way to make `kinetic-devel` build on Melodic that would be preferred.

**Comment by christian-rauch** [comment]
I am using the macro `GAZEBO_MAJOR_VERSION` to switch between the API versions and rebase on `kinetic-devel`. It should build now on kinetic and melodic.
I also added a missing install target for `robotiq_3f_gripper_joint_states`.

**Comment by atyshka** [comment]
+1 on merging this in. Melodic support is increasingly an expectation for ROS users.

**Comment by christian-rauch** [comment]
@jproberge @gavanderhoorn Did you have a chance to look at this?

**Comment by jproberge** [comment]
Hello @christian-rauch ! 

I'm very sorry for all the unexpected delays on my side, I'm abnormally busy at the moment. Nevertheless, I will definitely take a look at and review this PR very soon, no later than next Wednesday.

Thanks for submitting this PR, I'll come back to you very shortly.

**Review by jproberge — APPROVED** [review]
I've tested this on kinetic and melodic, works flawlessly. Changes make sense, I'm approving this.

**Pull request merged**
