### PR TITLE
ADD: WrenchStamped publisher, ROS_INFO to see if node is running

### PR DESCRIPTION
**Pull request by lorenz-halt**
... and node can be stopped with CTRL-C

### CODE REVIEW

**Comment by shaun-edwards** [comment]
In addition to other minor fixes, does this simply publish a standard message (Wrench) with data already contained within the custom robotiq message?

**Comment by lorenz-halt** [comment]
Exactly

**Comment by shaun-edwards** [comment]
+1 from me... @nicolaslauzier, what do you think

**Comment by nicolaslauzier** [comment]
Yes, I think we should have output a Wrench message from the beginning. This was not done simply because we didn't know this standard message. Also, thanks for the ros::ok() addition.

**Pull request merged**
