### PR TITLE
Changes according to discussion from previous pull request

### PR DESCRIPTION
**Pull request by lorenz-halt**
Delete ur_dependency and according test-case
Undo frame_id renaming

### CODE REVIEW

**Comment by shaun-edwards** [comment]
I'm confused?  Did you close the old PR and make a new one?

**Comment by lorenz-halt** [comment]
I did a new one, since the old one was already accepted...

**Comment by gavanderhoorn** [comment]
+1 from me.

@shaun-edwards: this reverts some changes that were introduced by #32 which were not bw-compatible and added user-specific pkg dependencies that should not have been added.

**Comment by gavanderhoorn** [comment]
@nicolaslauzier: could you merge this?

**Comment by gavanderhoorn** [comment]
Thank you.

**Comment by nicolaslauzier** [comment]
No problem, @gavanderhoorn . I really appreciate that you guys take the time to review these contributions. Most of our work is dedicated on the new hardware products so we don't have that much time to work on our ROS packages.

**Pull request merged**
